// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6lxFEi_FEWjzfxwmjddVvfJdPxwLJPZg',
    appId: '1:1054706704905:web:67d193aaeaa275305fced8',
    messagingSenderId: '1054706704905',
    projectId: 'lms-app-ae803',
    authDomain: 'lms-app-ae803.firebaseapp.com',
    storageBucket: 'lms-app-ae803.firebasestorage.app',
    measurementId: 'G-XLWL2JX2ML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1j-bNn9LIaqY9w6m1JmdqeGxwBNI_5uk',
    appId: '1:1054706704905:android:864128550c8c112d5fced8',
    messagingSenderId: '1054706704905',
    projectId: 'lms-app-ae803',
    storageBucket: 'lms-app-ae803.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxgQj6PYZ8lxWJrDivK0mTwNZcnaMgWEM',
    appId: '1:1054706704905:ios:d14f001b631b319d5fced8',
    messagingSenderId: '1054706704905',
    projectId: 'lms-app-ae803',
    storageBucket: 'lms-app-ae803.firebasestorage.app',
    androidClientId: '1054706704905-7b081qpgf6e9afso11jcujfos6fe7t7g.apps.googleusercontent.com',
    iosClientId: '1054706704905-4na363f2p0f404450fe21pau2qts0a9l.apps.googleusercontent.com',
    iosBundleId: 'com.example.lmsCollageAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxgQj6PYZ8lxWJrDivK0mTwNZcnaMgWEM',
    appId: '1:1054706704905:ios:d14f001b631b319d5fced8',
    messagingSenderId: '1054706704905',
    projectId: 'lms-app-ae803',
    storageBucket: 'lms-app-ae803.firebasestorage.app',
    androidClientId: '1054706704905-7b081qpgf6e9afso11jcujfos6fe7t7g.apps.googleusercontent.com',
    iosClientId: '1054706704905-4na363f2p0f404450fe21pau2qts0a9l.apps.googleusercontent.com',
    iosBundleId: 'com.example.lmsCollageAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6lxFEi_FEWjzfxwmjddVvfJdPxwLJPZg',
    appId: '1:1054706704905:web:17b1fac935da903b5fced8',
    messagingSenderId: '1054706704905',
    projectId: 'lms-app-ae803',
    authDomain: 'lms-app-ae803.firebaseapp.com',
    storageBucket: 'lms-app-ae803.firebasestorage.app',
    measurementId: 'G-GMB9JZVGR5',
  );
}
